apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
  namespace: skyhighlabs
spec:
  selector:
    matchLabels:
      app: guacamole
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      containers:
        - name: guacamole
          image: guacamole/guacamole:latest
          env:
            - name: GUACD_HOSTNAME
              value: "guacd"
            - name: MYSQL_HOSTNAME
              value: "mysql"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: "guacamole_db"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "Skyhigh12345!"
          ports:
            - containerPort: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacd
  namespace: skyhighlabs
spec:
  selector:
    matchLabels:
      app: guacd
  template:
    metadata:
      labels:
        app: guacd
    spec:
      containers:
        - name: guacd
          image: guacamole/guacd:latest
          ports:
            - containerPort: 4822

---

apiVersion: v1
kind: Service
metadata:
  name: guacamole
  namespace: skyhighlabs
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: guacamole

---

apiVersion: v1
kind: Service
metadata:
  name: guacd
  namespace: skyhighlabs
spec:
  ports:
    - port: 4822
      targetPort: 4822
  selector:
    app: guacd
