apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vxbr4200
  namespace: skyhighlabs
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "vxbr4200"
  }'

---

apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vxbr4201
  namespace: skyhighlabs
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "vxbr4201"
  }'

---

apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vxbr4202
  namespace: skyhighlabs
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "vxbr4202"
  }'

---

apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vxbr4203
  namespace: skyhighlabs
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "vxbr4203"
  }'

---

apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vxbr4204
  namespace: skyhighlabs
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "vxbr4204"
  }'

---

apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vxbr4205
  namespace: skyhighlabs
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "vxbr4205"
  }'

---

apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vxbr4206
  namespace: skyhighlabs
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "vxbr4206"
  }'

---

apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vxbr4207
  namespace: skyhighlabs
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "vxbr4207"
  }'

---

apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vxbr4208
  namespace: skyhighlabs
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "vxbr4208"
  }'

---

apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vxbr4209
  namespace: skyhighlabs
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "bridge",
    "bridge": "vxbr4209"
  }'
