apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: opnsense-dv
  namespace: skyhighlabs
spec:
  source:
    http:
      url: "https://s3.amazonaws.com/templates.byo.skyhighlabs.net/opnSense-template-thin.qcow2"
  pvc:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 32Gi

